[package]
name = "boids"
version = "0.1.0"
authors = ["Chris.Lee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = {version="0.5", features=[]}
glam = {version="*", features=["mint"]}
rand = "*"
palette = "*"